-- 새 테이블
CREATE TABLE SNS_LOGS (
	SNS_NO	INTEGER		NOT NULL,	-- 넘버
	URL_PARAM	VARCHAR(255)	NOT NULL,	-- 파라미터
	SCOPE		VARCHAR(255)	NOT NULL,	-- 범위
	PERIOD	VARCHAR(255)	NOT NULL,	-- 기간
	TITLE		VARCHAR(255)	NOT NULL,	-- 제목
	COLOR		VARCHAR(255)	NOT NULL,	-- 색
	VAL		INTEGER		NOT NULL	-- 초
);

-- 새 테이블 기본키
CREATE UNIQUE INDEX PK_SNS_LOGS
	ON SNS_LOGS ( -- 새 테이블
		SNS_NO ASC -- 넘버
	);

-- 일 인덱스
CREATE INDEX IX_SNS_LOGS
	ON SNS_LOGS ( -- 일
		URL_PARAM ASC -- 영문이름
	);

-- 새 테이블
ALTER TABLE SNS_LOGS
	MODIFY COLUMN SNS_NO INTEGER NOT NULL AUTO_INCREMENT,
	ADD
		CONSTRAINT PK_SNS_LOGS -- 새 테이블 기본키
		PRIMARY KEY (
			SNS_NO -- 넘버
		);
